version: "3.3"

services:
  zdir:
    image: "helloz/zdir:latest"
    container_name: ${CONTAINER_NAME}
    privileged: true
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6080"
    volumes:
      - "${ZDIR_DATA_DIR}:/opt/zdir/data"

networks:
  1panel-network:
    external: true
